# Generated by Django 3.2.15 on 2022-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='home/static/home/uploads')),
                ('image2', models.FileField(upload_to='home/static/home/uploads')),
            ],
        ),
    ]
